server:
  port: 8889
spring:
  profiles:
    active: dev # 数据源从dev中读取
  application:
    name: account
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
mybatis:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: com.riiyn.entity
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl