server:
  port: 8889
spring:
  application:
    name: account
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    url: jdbc:mysql://localhost:3306/oauth2?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 1023root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: com.riiyn.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
